#makefile for uploading and listening to the serial monitor. run these commands on the raspberrypi. 
monitor_arduino:
	/home/victor/Arduino/arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:uno arduino
	/home/victor/Arduino/arduino-cli monitor -p /dev/ttyUSB0